import React from 'react';

import styled from 'styled-components';

import Image from 'next/image';

import error from '@/images/404.png';

const Container = styled.div`
  padding: 2em;
`;
const ImageWrapper = styled.div`
  overflow: hidden;
  position: relative;
  height: 40vh;
  width: 100%;
  border-radius: 2em;
  margin-bottom: 1em;
`;

export default function Home() {
  // a 404 image generated by dall-e
  return (
    <Container>
      <ImageWrapper>
        <Image src={error} alt={'Error 404 vaporwave picture'} />
      </ImageWrapper>
    </Container>
  );
}
