import React from 'react';

import styled from 'styled-components';

import Image from 'next/image';

import texts from '@/styles/texts';
import { theme } from '@/styles/theme';

import error from '@/images/dalle-404.png';

// styles
const { h1, secondaryBody } = texts;
const { primaryBg } = theme;

const Content = styled.div`
  ${primaryBg};
  padding: 2em;
  display: flex;
  flex-direction: column;
  justify-content: center;
  justify-content: center;
  height: max-content;
  height: 150vh;
`;
const ImageWrapper = styled.div`
  overflow: hidden;
  position: relative;
  width: 50%;
  border-radius: 2em;
  align-self: center;
  @media (max-width: 680px) {
    width: 100%;
  }
`;

const Text = styled.h1`
  ${h1}
  text-align: center;
`;

const SecondText = styled.p`
  ${secondaryBody};
  padding-left: 1em;
  padding: 1em;
  text-align: center;
`;

// data
const data = {
  text: "We can't find that NFT",
  secondText: '(but here is a 🎁 made by DALL·E)',
};

export default function NotFound() {
  // a 404 image generated by dall-e
  return (
    <div>
      <Content>
        <Text>{data.text}</Text>
        <SecondText>{data.secondText}</SecondText>
        <ImageWrapper>
          <Image
            src={error}
            alt={'Error 404 DALL·E picture'}
            style={{ width: '100%', height: 'auto' }}
          />
        </ImageWrapper>
      </Content>
    </div>
  );
}
